### ISSUE TITLE
You currently have to exit MAME to get the plugin to recognize changes made to ssf.txt.

### ISSUE THREAD

**Issue by PL1-Arcade** [Jakobud/skipstartupframes#3]
You currently have to exit MAME to get the plugin to recognize changes made to ssf.txt.

https://forum.arcadecontrols.com/index.php/topic,169017.msg1775291.html#msg1775291

You mentioned that it is possible make the ssf.txt file reload on each game start/restart.

By "start/restart" do you mean _only_ exiting the game and relaunching it, **or** can a reload also be done as part of an "F3" (Reset) without exiting the game?

Either way would be great.

**Comment by Jakobud** [comment]
I'm working on this. I am setting it up to reload ssf.txt when you start a game OR restart a game. And some other features....

**Comment by PL1-Arcade** [comment]
v1.3.0 resolves this and several other minor issues.  Great job, Jake.  :1st_place_medal:
