### ISSUE TITLE
Changing plugin `Slow Motion` switch sometimes does not register, even after a reset/restart

### ISSUE THREAD

**Issue by PL1-Arcade** [Jakobud/skipstartupframes#8]
I like that plugin settings are retained when you F3 Reset or Restart a game **and** that changing the `Debug Mode` switch consistently registers immediately while you're still in the plugin menu during the countup to the Frame Target -- those are both working great.

The problem is when you try to change the `Slow Motion` switch after you're in slow motion mode.

That change appears to only register consistently when the frame count is past the Frame Target value **and** you turn off `Debug Mode` and `Slow Motion` **and then** you exit the game and restart.

Skip one of those three things and you're still stuck in slow motion, even though the switch is set to `No`.  This can be rather frustrating when testing a game with a large Frame Target like Flying Ball. (cflyball,12300)

1. Can the plugin check and apply both switch settings during both F3 reset and start/restart events?

2. Can the plugin check and apply the `Slow Motion` switch setting while still in the plugin menu like it does for the `Debug Mode` switch?
\- That would allow users to fast forward through most of the <i>really</i> long delays, then pause the game and switch it to slow motion to get a quicker and more accurate starting value.

Scott

**Comment by Jakobud** [comment]
I think I know the problem and I will look into it.

**Comment by PL1-Arcade** [comment]
> That change appears to only register consistently when the frame count is past the Frame Target value **and** you turn off `Debug Mode` and `Slow Motion` **and then** you exit the game and restart.
> 
> Skip one of those three things and you're still stuck in slow motion, even though the switch is set to `No`. This can be rather frustrating when testing a game with a large Frame Target like Flying Ball. (cflyball,12300)

Good news: There's another approach [mentioned by holub](https://github.com/orgs/mamedev/discussions/161) in your discussion on the MAME repo that appears to mostly work.

A `Slow Motion` switch change registers before reaching the Frame Target if you turn off `Debug Mode` then do a `Shift` + `F3` hard reset.


Scott

**Comment by PL1-Arcade** [comment]
Issue fixed in release v 2.0.0.

Scott

**Comment by Jakobud** [comment]
Yes once you enable debug mode and do a reset, you should be able to freely toggle debug and slow motion back and forth.
